"""empty message

Revision ID: 85119aa5462b
Revises: 
Create Date: 2018-02-11 01:06:59.595791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85119aa5462b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lovestory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_info', sa.String(length=120), nullable=True),
    sa.Column('img_url', sa.String(length=200), nullable=True),
    sa.Column('story_text', sa.String(length=500), nullable=True),
    sa.Column('satus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img_url'),
    sa.UniqueConstraint('satus'),
    sa.UniqueConstraint('story_text'),
    sa.UniqueConstraint('user_info')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lovestory')
    # ### end Alembic commands ###
